pod 'AFNetworking', '~> 3.0'
pod 'UITableView+FDTemplateLayoutCell_Bell', '~> 1.5.0'
pod 'FXBlurView', '~> 1.6.4'
pod 'IQKeyboardManager', '~> 4.0.4'
pod 'Masonry', '~> 1.0.1'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'MJExtension', '~> 3.0.11'
pod 'MJRefresh', '~> 3.1.10'
pod 'SDWebImage', '~> 3.8.1'
pod 'STPopup', '~> 1.7.0'
pod 'YYCache', '~> 1.0.3'
pod 'YYText', '~> 1.0.5'
pod 'CYLTabBarController'
pod 'SDCycleScrollView', '~> 1.65'